name: MOSS-MINIMAL

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hello:
    runs-on: ubuntu-24.04
    steps:
      - name: Hello
        run: |
          echo "hello from github actions"
          uname -a
          date -u
